export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen text-slate-900">
        <header className="app-header">
          <div className="container flex items-center justify-between py-4">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-accent rounded flex items-center justify-center text-white font-bold">R</div>
              <div>
                <div className="text-lg font-semibold">Rummy Scorecard</div>
                <div className="text-xs muted">Minimal · Modern · Fast</div>
              </div>
            </div>
          </div>
        </header>
        <main className="container py-8">{children}</main>
      </body>
    </html>
  )
}
